export const site = {
  name: "Aquaclear Water Management",
  url: "https://www.aquaclearwatermanagement.com/",
  email: "info@aquaclearwatermanagement.com",
  mobile: "07814 741491",
  phone: "01646 641560",
  street: "16 Angle Village",
  town: "Pembrokeshire", 
  country: "Wales",
  countryCode: "GB",
  postCode: "SA71 5AT",
  theme: "#0A5A99",
  tagline: "UK Waterway Management Specialists.",
  short: "Waterway Management & Amphibious Machinery",
  emailTemplate: "enquiry-template",
  language: "en-GB",
  repo: "aquaclear-v1",

  social: {
    facebook: "https://www.facebook.com/profile.php?id=100068576013925&fref=ts#",
    instagram: "",
    linkedin: "https://www.linkedin.com/in/sean-harries-7a3a58365/",
    youtube: "",
    x: "https://x.com/aquaclearwm",
  },
}